"""Add EmergingIssue table

Revision ID: 0765be806706
Revises: 46b1c7c8c4de
Create Date: 2026-09-12 12:23:40.597866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0765be806706'
down_revision: Union[str, Sequence[str], None] = '46b1c7c8c4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emerging_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('signal_score', sa.Float(), nullable=True),
    sa.Column('signal_level', sa.String(), nullable=True),
    sa.Column('contributing_factors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emerging_issues_id'), 'emerging_issues', ['id'], unique=False)
    op.create_index(op.f('ix_emerging_issues_topic_id'), 'emerging_issues', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emerging_issues_topic_id'), table_name='emerging_issues')
    op.drop_index(op.f('ix_emerging_issues_id'), table_name='emerging_issues')
    op.drop_table('emerging_issues')
    # ### end Alembic commands ###
