"""Add PostAnalysis

Revision ID: 0d8c9e879b7b
Revises: 0b4440ffccc3
Create Date: 2026-09-12 12:03:21.902924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8c9e879b7b'
down_revision: Union[str, Sequence[str], None] = '0b4440ffccc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('duplicates_removed', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_id'), 'pipeline_runs', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_source'), 'pipeline_runs', ['source'], unique=False)
    op.create_table('post_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_analysis_id'), 'post_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_post_analysis_post_id'), 'post_analysis', ['post_id'], unique=True)
    op.add_column('data_sources', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('data_sources', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_column('data_sources', 'base_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('base_url', sa.VARCHAR(), nullable=True))
    op.drop_column('data_sources', 'created_at')
    op.drop_column('data_sources', 'is_active')
    op.drop_index(op.f('ix_post_analysis_post_id'), table_name='post_analysis')
    op.drop_index(op.f('ix_post_analysis_id'), table_name='post_analysis')
    op.drop_table('post_analysis')
    op.drop_index(op.f('ix_pipeline_runs_source'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
