"""phase_1_emerging_issues_schema

Revision ID: 9176e6f6d24d
Revises: 0765be806706
Create Date: 2026-09-20 09:46:59.731996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9176e6f6d24d'
down_revision: Union[str, Sequence[str], None] = '0765be806706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emerging_issues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('signal_score')
        batch_op.drop_column('signal_level')
        batch_op.drop_column('contributing_factors')
        batch_op.drop_column('topic_id')

    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sentiment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emotion', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_posts', schema=None) as batch_op:
        batch_op.drop_column('emotion')
        batch_op.drop_column('sentiment')
        batch_op.drop_column('normalized_text')

    with op.batch_alter_table('emerging_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('contributing_factors', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('signal_level', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('signal_score', sa.FLOAT(), nullable=True))
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'])

    # ### end Alembic commands ###
